skip_tags: true
clone_depth: 50

os: Visual Studio 2015

environment:
  matrix:
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86"
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86_64"

platform:
    - x64

build_script:
  - cmd: SET MKL_NUM_THREADS=1
  - cmd: SET NUMEXPR_NUM_THREADS=1
  - cmd: SET OMP_NUM_THREADS=1
  - cmd: SET OPENBLAS_NUM_THREADS=1
  - ps: Start-FileDownload "https://repo.continuum.io/miniconda/Miniconda$env:PY_MAJOR_VER-latest-Windows-$env:PYTHON_ARCH.exe" C:\Miniconda.exe; echo "Finished downloading miniconda"
  - cmd: C:\Miniconda.exe /S /D=C:\Py
  - cmd: SET PATH=C:\Py;C:\Py\Scripts;C:\Py\Library\bin;%PATH%
  - cmd: conda config --set always_yes yes
  - cmd: conda update conda --quiet
  - cmd: conda install numpy cython pytest pandas scipy patsy statsmodels matplotlib numba nbconvert nbformat pip pyyaml setuptools pyqt pyparsing --quiet
  - cmd: python -m pip install --upgrade pip
  - cmd: pip install pytest-xdist!=1.30 property_cached
  - cmd: pip install -e .

test_script:
  - cmd: pytest -n 2 arch -m "(not slow)" --durations=25
